[workspace]
resolver = '2'
members = [
  'crates/core',
  'crates/plato',
  'crates/emulator',
  'crates/importer',
  'crates/fetcher',
  'crates/epub_edit',
  'crates/epub_editor',
  'crates/plato-android',
]
exclude = [
]

[workspace.package]
edition = '2021'
version = '0.9.45'
license = 'MIT'
rust-version = "1.87"

[workspace.dependencies]
anyhow = "1.0.102"
bitflags = "2.11.1"
env_logger = "0.11.10"
indexmap = { version = "2.14.0", features = ["serde"] }
log = "0.4.29"
nix = { version = "0.31.2", features = ["fs", "ioctl"] }
regex = "1.12.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
uuid = { version = "1.23.1", features = ["v4"] }
zip = "8.5.1"

[profile.release-minsized]
inherits = "release"
panic = "abort"
codegen-units = 4
opt-level = "z"
lto = "thin"
strip = true

[profile.release-arm]
inherits = "release"
codegen-units = 4
lto = "thin"
strip = true
opt-level = 3

[profile.release-arm64]
inherits = "release"
codegen-units = 4
lto = "thin"
strip = true
opt-level = 3

[profile.release-ios]
inherits = "release"
codegen-units = 4
lto = "thin"
strip = true
opt-level = 3
panic = "abort"

[profile.release-embedded]
inherits = "release"
codegen-units = 4
lto = "thin"
opt-level = "s"
strip = true
debug = false

[profile.release]
lto = "thin"
codegen-units = 16

[profile.dev]
opt-level = 0
debug = true
incremental = true

[profile.bench]
inherits = "release"
debug = true
lto = "thin"
