[package]
name = "plato_search"
version = "0.9.45"
edition = "2021"
license = "AGPLv3"

[dependencies]
plato_error = { path = "../error" }
plato-ai = { path = "../ai" }
rusqlite = { version = "0.33", features = ["bundled"] }
anyhow = "1.0"
tokio = { version = "1.43", features = ["full"] }
zip = { version = "8.6.0", features = ["deflate"] }

[lib]
path = "src/lib.rs"
