[workspace]

[package]
name = "plato-android"
version = "0.9.45"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
plato-core = { path = "../core" }
android-activity = { version = "0.6.1", features = ["native-activity"] }
ndk = "0.9.0"
ndk-context = "0.1.1"
ndk-glue = "0.7.0"
android_logger = "0.15.1"
log = "0.4.29"
