[package]
authors = ["Bastien Dejean <nihilhill@gmail.com>"]
name = "plato"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Document reader and library manager for e-ink devices"
repository = "https://github.com/jcn363/plato"

[[bin]]
name = "plato"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.43", features = ["full"] }
plato-core = { path = "../core", features = ["ocr"] }

[package.metadata.deb]
maintainer = "Plato Project <https://github.com/jcn363/plato>"
copyright = "2024-2026, Plato Contributors"
assets = [
    ["target/release/plato", "usr/bin/", "755"],
    ["../../README.md", "usr/share/doc/plato/", "644"],
    ["../../CHANGES.md", "usr/share/doc/plato/", "644"],
    ["../../LICENSE-AGPLv3", "usr/share/doc/plato/", "644"],
]
depends = "$auto"
section = "text"
priority = "optional"
conf-files = ["/etc/plato/settings.toml"]
